Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,7 +27,6 @@ jobs:
         run: |
           pwd 
           echo "$KUBECONFIG_FILE" > kubeconfig.yml
-          cat kubeconfig.yaml  # Print the kubeconfig file content (added step)
           kubectl config use-context $KUBE_CONTEXT --kubeconfig=kubeconfig.yml
           kubectl apply --kubeconfig=kubeconfig.yml --namespace=$KUBE_NAMESPACE -f wisecow_deploy.yml
           ls /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/kubernetes-wisecow
@@ -35,3 +34,11 @@ jobs:
           # kubectl rollout status deployment/wisecow-deployment
           # kubectl apply -f /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/kubernetes-wisecow/ --validate=false
           # Add additional apply commands for other YAML files if needed
+      - name: Print kubeconfig file  # Add this step
+        run: |
+          if [ -f kubeconfig.yaml ]; then
+            cat kubeconfig.yaml
+          else
+            echo "Error: kubeconfig.yaml not found"
+            exit 1
+          fi
